// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'programs/programs.dart';
import 'users/user_profile/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7921616601747497635),
    name: 'Program',
    lastPropertyId: const obx_int.IdUid(6, 142164315650130750),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4533999654364926756),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3581968683899267061),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2737126932153794040),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7918003514796020674),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3538380349880036662),
        name: 'editing',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 142164315650130750),
        name: 'fees',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 7050458213461410191),
        name: 'applicants',
        targetId: const obx_int.IdUid(2, 4471815993768337905),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4471815993768337905),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(10, 4872331494486906791),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2647843429122930378),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6525710342345634105),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7363062978476946989),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4220583770545314617),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8488591836272135695),
        name: 'educations',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6898282076625673772),
        name: 'experiences',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2403273909876709062),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7980883481467864143),
        name: 'dateOfBirth',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 162892024970831789),
        name: 'highSchool',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4872331494486906791),
        name: 'gpa',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 3325372730888395724),
        name: 'programs',
        targetId: const obx_int.IdUid(1, 7921616601747497635),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4471815993768337905),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(2, 3325372730888395724),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Program: obx_int.EntityDefinition<Program>(
      model: _entities[0],
      toOneRelations: (Program object) => [],
      toManyRelations: (Program object) => {
        obx_int.RelInfo<Program>.toMany(1, object.id): object.applicants,
      },
      getId: (Program object) => object.id,
      setId: (Program object, int id) {
        object.id = id;
      },
      objectToFB: (Program object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final categoryOffset = fbb.writeString(object.category);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addBool(4, object.editing);
        fbb.addInt64(5, object.fees);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Program()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..category = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..editing = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..fees = const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
        obx_int.InternalToManyAccess.setRelInfo<Program>(
          object.applicants,
          store,
          obx_int.RelInfo<Program>.toMany(1, object.id),
        );
        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[1],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {
        obx_int.RelInfo<User>.toMany(2, object.id): object.programs,
      },
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        final passwordOffset = fbb.writeString(object.password);
        final educationsOffset = fbb.writeString(object.educations);
        final experiencesOffset = fbb.writeString(object.experiences);
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        final highSchoolOffset = fbb.writeString(object.highSchool);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, passwordOffset);
        fbb.addOffset(4, educationsOffset);
        fbb.addOffset(5, experiencesOffset);
        fbb.addOffset(6, phoneNumberOffset);
        fbb.addInt64(7, object.dateOfBirth?.millisecondsSinceEpoch);
        fbb.addOffset(8, highSchoolOffset);
        fbb.addFloat64(9, object.gpa);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateOfBirthValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = User()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..email = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..password = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..educations = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..experiences = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..phoneNumber = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..dateOfBirth = dateOfBirthValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateOfBirthValue)
          ..highSchool = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..gpa = const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
        obx_int.InternalToManyAccess.setRelInfo<User>(
          object.programs,
          store,
          obx_int.RelInfo<User>.toMany(2, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Program] entity fields to define ObjectBox queries.
class Program_ {
  /// See [Program.id].
  static final id = obx.QueryIntegerProperty<Program>(
    _entities[0].properties[0],
  );

  /// See [Program.name].
  static final name = obx.QueryStringProperty<Program>(
    _entities[0].properties[1],
  );

  /// See [Program.category].
  static final category = obx.QueryStringProperty<Program>(
    _entities[0].properties[2],
  );

  /// See [Program.description].
  static final description = obx.QueryStringProperty<Program>(
    _entities[0].properties[3],
  );

  /// See [Program.editing].
  static final editing = obx.QueryBooleanProperty<Program>(
    _entities[0].properties[4],
  );

  /// See [Program.fees].
  static final fees = obx.QueryIntegerProperty<Program>(
    _entities[0].properties[5],
  );

  /// see [Program.applicants]
  static final applicants = obx.QueryRelationToMany<Program, User>(
    _entities[0].relations[0],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[1].properties[0]);

  /// See [User.name].
  static final name = obx.QueryStringProperty<User>(_entities[1].properties[1]);

  /// See [User.email].
  static final email = obx.QueryStringProperty<User>(
    _entities[1].properties[2],
  );

  /// See [User.password].
  static final password = obx.QueryStringProperty<User>(
    _entities[1].properties[3],
  );

  /// See [User.educations].
  static final educations = obx.QueryStringProperty<User>(
    _entities[1].properties[4],
  );

  /// See [User.experiences].
  static final experiences = obx.QueryStringProperty<User>(
    _entities[1].properties[5],
  );

  /// See [User.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<User>(
    _entities[1].properties[6],
  );

  /// See [User.dateOfBirth].
  static final dateOfBirth = obx.QueryDateProperty<User>(
    _entities[1].properties[7],
  );

  /// See [User.highSchool].
  static final highSchool = obx.QueryStringProperty<User>(
    _entities[1].properties[8],
  );

  /// See [User.gpa].
  static final gpa = obx.QueryDoubleProperty<User>(_entities[1].properties[9]);

  /// see [User.programs]
  static final programs = obx.QueryRelationToMany<User, Program>(
    _entities[1].relations[0],
  );
}
